# Filtering data to seperate 5 states

In [1]:
import pandas as pd

In [2]:
all_data = pd.read_excel("GWQ_2010-2018.xlsx",sheet_name="Sheet1")

In [4]:
all_data.shape

(85197, 37)

In [5]:
all_data = all_data.dropna(subset=["FLUORIDE"])

In [6]:
all_data.shape

(83992, 37)

In [11]:
all_data.head()

,SITE_ID,WRIS ID,LATITUDE,LONGITUDE,SITE_TYPE,STATE_NAME,DISTRICT_NAME,TAHSIL_NAME,BLOCK_NAME,SITE_NAME,...,FLUORIDE,SAR,RSC,SiO2,PO4,TDS,Turbidity,%Na,Arsenic,LR. No
0,W115159092441001,W23881,11.866389,92.736111,Dug Well,Andaman And Nicobar,A & N Islands,Ferrargunj,South Andaman,Shoal Bay– 15 No.,...,0.37,NaN,NaN,13.97,NaN,217.748,NaN,NaN,NaN,NaN
1,New,W38814,12.186944,92.791667,Dug Well,Andaman And Nicobar,A & N Islands,Middle Andaman,Baratang Island,South Creek (Sundergarh),...,0.24,0,0,15.14,0,360.745,,,0,0
2,W123014092513301,W24095,12.503889,92.859167,Dug Well,Andaman And Nicobar,A & N Islands,Middle Andaman,Mayabunder,Bakultala,...,0.96,0,0,7.67,0,239.246,NaN,NaN,0,NaN
3,W123129092581301,W24112,12.524722,92.970278,Dug Well,Andaman And Nicobar,A & N Islands,Middle Andaman,Mayabunder,Nimbutala,...,1.02,0,0,0,0,253.22,NaN,NaN,0,NaN
4,W123030092573801,W24098,12.508333,92.960556,Dug Well,Andaman And Nicobar,A & N Islands,Middle Andaman,Mayabunder,Padmanavapuram,...,0.74,0,0,10.34,0,185.361,NaN,NaN,0,NaN

In [15]:
Rajasthan = all_data.loc[all_data['STATE_NAME']=='Rajasthan']

In [16]:
Rajasthan

,SITE_ID,WRIS ID,LATITUDE,LONGITUDE,SITE_TYPE,STATE_NAME,DISTRICT_NAME,TAHSIL_NAME,BLOCK_NAME,SITE_NAME,...,FLUORIDE,SAR,RSC,SiO2,PO4,TDS,Turbidity,%Na,Arsenic,LR. No
63518,W260200075060001,W13591,"26°2'0"" N","75°6'0"" E",Dug Well,Rajasthan,Ajmer,Arain,Arain,Ajagara,...,15.72,15.989604,4.673212,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63519,W260200075060001,W13591,"26°2'0"" N","75°6'0"" E",Dug Well,Rajasthan,Ajmer,Arain,Arain,Ajagara,...,1.368,26.347434,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63520,W260200075060001,W13591,"26°2'0"" N","75°6'0"" E",Dug Well,Rajasthan,Ajmer,Arain,Arain,Ajagara,...,1.4,26.319585,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63521,W260200075060001,W13591,"26°2'0"" N","75°6'0"" E",Dug Well,Rajasthan,Ajmer,Arain,Arain,Ajagara,...,1.4,26.319585,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63522,W260200075060001,W13591,"26°2'0"" N","75°6'0"" E",Dug Well,Rajasthan,Ajmer,Arain,Arain,Ajagara,...,1.25,14.63,3.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68939,W240500073510001,W14586,"24°5'0"" N","73°51'0"" E",Dug Well,Rajasthan,Udaipur,Sarara,Sarara,Semri,...,3.2,6.09174,5.379605,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68940,W240500073510001,W14586,"24°5'0"" N","73°51'0"" E",Dug Well,Rajasthan,Udaipur,Sarara,Sarara,Semri,...,3.4,6.257336,5.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68941,W240500073510001,W14586,"24°5'0"" N","73°51'0"" E",Dug Well,Rajasthan,Udaipur,Sarara,Sarara,Semri,...,3.6,6.11413,5.490477,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68942,W240500073510001,W14586,"24°5'0"" N","73°51'0"" E",Dug Well,Rajasthan,Udaipur,Sarara,Sarara,Semri,...,3.4,4.02,1.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68943,W240500073510001,W14586,"24°5'0"" N","73°51'0"" E",Dug Well,Rajasthan,Udaipur,Sarara,Sarara,Semri,...,0.12,6.18,151.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# done
# Rajasthan.to_excel("Rajasthan.xlsx",sheet_name='Sheet1')

In [18]:
Andhra_Pradesh = all_data.loc[all_data['STATE_NAME']=='Andhra Pradesh']
Andhra_Pradesh

,SITE_ID,WRIS ID,LATITUDE,LONGITUDE,SITE_TYPE,STATE_NAME,DISTRICT_NAME,TAHSIL_NAME,BLOCK_NAME,SITE_NAME,...,FLUORIDE,SAR,RSC,SiO2,PO4,TDS,Turbidity,%Na,Arsenic,LR. No
339,W135900077460001,W04180,"13°59'0"" N","77°46'0"" E",Dug Well,Andhra Pradesh,Anantapur,Amarapuram,Amarapuram,Gorantla,...,2.2,5.1,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,W135900077460001,W04180,"13°59'0"" N","77°46'0"" E",Dug Well,Andhra Pradesh,Anantapur,Amarapuram,Amarapuram,Gorantla,...,1.2,ND,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,W135900077460001,W04180,"13°59'0"" N","77°46'0"" E",Dug Well,Andhra Pradesh,Anantapur,Amarapuram,Amarapuram,Gorantla,...,3.83,3.65,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,W135830077524001,W04183,"13°58'30"" N","77°52'40"" E",Dug Well,Andhra Pradesh,Anantapur,Amarapuram,Amarapuram,Govinavaripalli,...,3.8,6.1,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,W135830077524001,W04183,"13°58'30"" N","77°52'40"" E",Dug Well,Andhra Pradesh,Anantapur,Amarapuram,Amarapuram,Govinavaripalli,...,2.1,2.27,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4953,W163200081390001,W05217,"16°32'0"" N","81°39'0"" E",Dug Well,Andhra Pradesh,West Godavari,Veeravasaram,Veeravasaram,Veeravasaram,...,0.11,11.51,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4954,W163200081390001,W05217,"16°32'0"" N","81°39'0"" E",Dug Well,Andhra Pradesh,West Godavari,Veeravasaram,Veeravasaram,Veeravasaram,...,0.05,6.6,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4955,W163200081390001,W05217,"16°32'0"" N","81°39'0"" E",Dug Well,Andhra Pradesh,West Godavari,Veeravasaram,Veeravasaram,Veeravasaram,...,0.27,NaN,NaN,NaN,NaN,1512,NaN,NaN,NaN,NaN
4956,W163200081390001,W05217,16.533333,81.65,MONITORING,Andhra Pradesh,West Godavari,Veeravasaram,Veeravasaram,Veeravasaram,...,0.4,6.86,-0.01,NaN,NaN,NaN,NaN,NaN,*,W163200081390001
4957,W163200081390001,W05217,16.5333,81.65,MONITORING,Andhra Pradesh,West Godavari,Veeravasaram,Veeravasaram,Veeravasaram,...,0.19,3.87,2.3,0,0,0,NaN,NaN,*,NaN

In [19]:
# done
# Andhra_Pradesh.to_excel("Andhra_Pradesh.xlsx",sheet_name='Sheet1')

In [20]:
West_Bengal = all_data.loc[all_data['STATE_NAME']=='West Bengal']
West_Bengal

,SITE_ID,WRIS ID,LATITUDE,LONGITUDE,SITE_TYPE,STATE_NAME,DISTRICT_NAME,TAHSIL_NAME,BLOCK_NAME,SITE_NAME,...,FLUORIDE,SAR,RSC,SiO2,PO4,TDS,Turbidity,%Na,Arsenic,LR. No
81154,New,W40678,22.87,86.78,Dug well,West Bengal,Bakura,Akhuta More,Ranibandh,Ranibandh (Akhuta More),...,0.13,0,0,0,0.682,308.48,,,0,0
81155,W232514087063701,W10143,23.4,87.11,Dug well,West Bengal,Bakura,Amarkanan,Gangajal Ghati,Gangajalghati,...,0.12,0,0,0,0.633,526.08,NaN,NaN,0,NaN
81156,New,W40679,23.31,87.11,Dug well,West Bengal,Bakura,Ba0Hakona,Bankura Ii,Borjora,...,0.09,0,0,0,16.93,355.84,,,0,0
81157,New,W40680,23.31,86.96,Dug well,West Bengal,Bakura,Babupara,Chatna,Chatna,...,0.18,0,0,0,BDL,1072,,,0,0
81158,New,W40681,23.07,86.89,Dug well,West Bengal,Bakura,Baharamuri,Khatra I,Khatra-I,...,0.16,0,0,0,0.519,695.04,,,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85192,New,W40943,22.51,87.33,Dug Well,West Bengal,West Midnapur,Salboni,Salboni,Gobru,...,0,0,0,0,0.197,75.584,,,0,0
85193,W220857087092501,W10716,22.18,87.16,Dug Well,West Bengal,West Midnapur,Sankrail,Binpur I,Kultikri,...,0.05,0,0,0,BDL,316.16,NaN,NaN,0,NaN
85194,New,W40944,22.58,87.52,Dug Well,West Bengal,West Midnapur,Saranga,Keshpur,Saranga,...,0.38,0,0,0,0.211,307.776,,,0,0
85195,New,W40945,22.47,87.02,Dug Well,West Bengal,West Midnapur,Sevayatan,Jhargram,Sevayatan,...,0,0,0,0,0.183,25.2544,,,0,0
85196,New,W40946,22.61,86.81,Dug Well,West Bengal,West Midnapur,Silda,Binpur-ii,Muohi Bundh,...,0.34,0,0,0,0.873,339.2,,,0,0

In [21]:
# done
# West_Bengal.to_excel("West_Bengal.xlsx",sheet_name='Sheet1')

In [22]:
Telangana = all_data.loc[all_data['STATE_NAME']=='Telangana']
Telangana

,SITE_ID,WRIS ID,LATITUDE,LONGITUDE,SITE_TYPE,STATE_NAME,DISTRICT_NAME,TAHSIL_NAME,BLOCK_NAME,SITE_NAME,...,FLUORIDE,SAR,RSC,SiO2,PO4,TDS,Turbidity,%Na,Arsenic,LR. No
72970,W192200079170001,W03811,"19°22'0"" N","79°17'0"" E",Dug Well,Telangana,Adilabad,Asifabad,Asifabad,Asifabad,...,1.51,NaN,NaN,NaN,NaN,558,NaN,NaN,NaN,NaN
72971,W193816078303001,W26159,"19°38'16"" N","78°30'30"" E",Dug Well,Telangana,Adilabad,Adilabad,Adilabad,Mavala Dw 2012,...,0.22,2.682059,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72972,W193816078303001,W26159,"19°38'16"" N","78°30'30"" E",Dug Well,Telangana,Adilabad,Adilabad,Adilabad,Mavala Dw 2012,...,0.2,0.98,-6.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72973,W193816078303001,W26159,"19°38'16"" N","78°30'30"" E",Dug Well,Telangana,Adilabad,Adilabad,Adilabad,Mavala Dw 2012,...,0.22,0.96,-5.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72974,W193816078303001,W26159,19.637778,78.508333,MONITORING,Telangana,Adilabad,Adilabad,Adilabad,Mavala Dw 2012,...,0.42,2.26,-4.9,NaN,NaN,NaN,NaN,NaN,*,W193816078303001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75882,W172859079462301,W25563,17.483056,79.773056,MONITORING,Telangana,Warangal,Thorrur,Thorrur,Beerishettigudem Dw13,...,2.89,7.18,4.59,NaN,NaN,NaN,NaN,NaN,*,W172859079462301
75883,W172859079462301,W25563,17.4831,79.7731,MONITORING,Telangana,Warangal,Thorrur,Thorrur,Beerishettigudem Dw13,...,2.14,5.58,4,0,0,0,NaN,NaN,*,NaN
75884,New,W40538,17.830556,79.595278,MONITORING,Telangana,Warangal,Waradannapet,Waradannapet,Ellendadw15,...,1.68,8.21,7.39,NaN,NaN,NaN,NaN,NaN,*,W174950079354301
75885,New,W40538,17.8306,79.5953,MONITORING,Telangana,Warangal,Waradannapet,Waradannapet,Ellendadw15,...,1.53,6.28,5.3,0,0,0,NaN,NaN,*,NaN
75886,New,W37730,17.800169,79.597134,Dug Well,Telangana,Warangal,Wardhannapeta,Wardhannapeta,Yellenda,...,2.45,NaN,NaN,NaN,NaN,1015,NaN,NaN,NaN,NaN

In [23]:
# done
# Telangana.to_excel("Telangana.xlsx",sheet_name='Sheet1')

In [24]:
Tamil_Nadu = all_data.loc[all_data['STATE_NAME']=='Tamil Nadu']
Tamil_Nadu

,SITE_ID,WRIS ID,LATITUDE,LONGITUDE,SITE_TYPE,STATE_NAME,DISTRICT_NAME,TAHSIL_NAME,BLOCK_NAME,SITE_NAME,...,FLUORIDE,SAR,RSC,SiO2,PO4,TDS,Turbidity,%Na,Arsenic,LR. No
68944,New,W40047,11.081,79.1407,Dug Well,Tamil Nadu,Ariyalur,Ariyalur,Ariyalur,Mangathy,...,0.05,0,0,0,0,65.52,0,,0,0
68945,New,W40048,11.1401,79.0786,Dug Well,Tamil Nadu,Ariyalur,Ariyalur,Ariyalur,Vazhavanthankuppam,...,0.9,0,0,0,0,1014.3,0,,0,0
68946,New,W40049,11.2,79.32,Dug Well,Tamil Nadu,Ariyalur,Jayamkondam,Jayankondam,Thulnkurchi,...,0.05,0,0,0,0,2072.7,,,0,0
68947,New,W40045,11.155,79.1901,Dug Well,Tamil Nadu,Ariyalur,Sendurai,Ariyalur,Elaiyur,...,0.54,0,0,0,0,1644.3,0,,0,0
68948,New,W40050,11.1401,79.0786,Dug Well,Tamil Nadu,Ariyalur,T.Kallupatti,Ariyalur,Kolluveerampatti,...,2.432369,0,0,0,0,1423.8,,,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72965,W093500077571501,W02916,"9°35'0"" N","77°57'15"" E",Dug Well,Tamil Nadu,Virudhundgar,Virudhunagar,Virudhundgar,Virudundgar,...,1.48,8.704575,2.69835,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72966,W093500077571501,W02916,"9°35'0"" N","77°57'15"" E",Dug Well,Tamil Nadu,Virudhundgar,Virudhunagar,Virudhundgar,Virudundgar,...,1.5,ND,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72967,W093749077383001,W02924,"9°37'49"" N","77°38'30"" E",Dug Well,Tamil Nadu,Virudhundgar,Virudhunagar,Watrap,Watrap,...,1.16,1.442166,0.289331,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72968,W093749077383001,W02924,"9°37'49"" N","77°38'30"" E",Dug Well,Tamil Nadu,Virudhundgar,Virudhunagar,Watrap,Watrap,...,1.42,2.377186,1.604584,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72969,W093749077383001,W02924,"9°37'49"" N","77°38'30"" E",Dug Well,Tamil Nadu,Virudhundgar,Virudhunagar,Watrap,Watrap,...,1.65,ND,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# done
# Tamil_Nadu.to_excel("Tamil_Nadu.xlsx",sheet_name='Sheet1')